Added support for Loadbalancer with TestPMD

diff --git a/testpmd/scripts/testpmd-wrapper b/testpmd/scripts/testpmd-wrapper
--- a/testpmd/scripts/testpmd-wrapper
+++ b/testpmd/scripts/testpmd-wrapper
@@ -2,9 +2,14 @@
 
 set -ex
 
+RUN_MAC=${run_mac:=1}
+RUN_APP=${run_app:=1}
+
 LOG_DIR="/var/log/testpmd"
 [ -d $LOG_DIR ] || mkdir -p $LOG_DIR
 rm -rf /var/log/testpmd/*
+
+MODE=${MODE:-"fwd"}
 
 if [ -z NETWORK_NAME_LIST ]; then
     echo "NETWORK_NAME_LIST is empty, exiting.."
@@ -50,21 +55,56 @@ fi
 
 STATS_PERIOD=${stats_period:=1}
 RUN="/usr/local/bin/testpmd-run"
-echo "testpmd -l $LCORES $PCI $@ --stats-period ${STATS_PERIOD} --cmdline-file /root/testpmd-runtime-cmds.txt 2>&1 | tee /var/log/testpmd/app.log" > $RUN
+CMD="testpmd"
+CMD="${CMD} -l $LCORES"
+CMD="${CMD} $PCI"
+CMD="${CMD} $@"
+CMD="${CMD} --stats-period ${STATS_PERIOD}"
+CMD="${CMD} --cmdline-file /root/testpmd-runtime-cmds.txt"
+
+if [[ "$MODE" == "lb" ]]; then
+    CNF_PCI=""
+    IFS=',' read -r -a NETWORK_ARRAY <<< "$CNF_APP_NETWORK_NAME_LIST"
+    for item in "${NETWORK_ARRAY[@]}"; do
+        IFS='/' read -r -a RES_ARRAY <<< "$item"
+        NAME="PCIDEVICE_OPENSHIFT_IO_${RES_ARRAY[1]^^}"
+        if [ -z ${!NAME} ]; then
+            echo "Could not find ${NAME} with PCI address, exiting"
+            exit 1
+        fi
+        IFS=',' read -r -a PCI_ARRAY <<< "${!NAME}"
+        for pci_item in "${PCI_ARRAY[@]}"; do
+            CNF_PCI+=" --dut-pci ${pci_item} "
+        done
+    done
+    ETH_PEER="${ETH_PEER_MACS}"
+    CMD="${CMD} --enable-lb "
+    CMD="${CMD} ${CNF_PCI} "
+fi
+
+CMD="${CMD} 2>&1 | tee /var/log/testpmd/app.log"
+echo "${CMD}" > $RUN
 chmod +x $RUN
 
-# Fetches mac address from pci using macaddr DPDK custom application
-# Mac address is written to tile /tmp/macaddr.txt
-# Fetch macaddress before running testpmd to avoid resource busy error
-if [ -f /var/lib/testpmd/macaddr.txt ]; then
-    rm -f /var/lib/testpmd/macaddr.txt
+if [[ "$RUN_MAC" == "0" ]]; then
+    echo "run_mac is set to 0, waiting..."
+    sleep infinity
 fi
-n=0
-until [ "$n" -ge 5 ]; do
-   macaddr $PCI && break
-   n=$((n+1))
-   sleep 1
-done
+
+if [[ "$MODE" != "lb" ]]; then
+    # Fetches mac address from pci using macaddr DPDK custom application
+    # Mac address is written to tile /tmp/macaddr.txt
+    # Fetch macaddress before running testpmd to avoid resource busy error
+    if [ -f /var/lib/testpmd/macaddr.txt ]; then
+        rm -f /var/lib/testpmd/macaddr.txt
+    fi
+    n=0
+    until [ "$n" -ge 5 ]; do
+       macaddr $PCI && break
+       n=$((n+1))
+       sleep 1
+    done
+fi
 
 function sig_term() {
     echo $(date +"%F %T,%3N") > /var/log/testpmd/sigterm-received.log
@@ -74,7 +114,6 @@ function sig_term() {
 }
 trap sig_term SIGTERM
 
-RUN_APP=${run_app:=1}
 if [[ $RUN_APP == "1" ]]; then
     testpmd-run
 else
