v0.2.0: Separated server and application containers

diff --git a/testpmd/scripts/testpmd-wrapper b/testpmd/scripts/testpmd-wrapper
--- a/testpmd/scripts/testpmd-wrapper
+++ b/testpmd/scripts/testpmd-wrapper
@@ -14,6 +14,8 @@ fi
 PCI=""
 IFS=',' read -r -a NETWORK_ARRAY <<< "$NETWORK_NAME_LIST"
 
+TESTPMD_ENV="/var/lib/testpmd/env.txt"
+echo "" > $TESTPMD_ENV
 for item in "${NETWORK_ARRAY[@]}"; do
     IFS='/' read -r -a RES_ARRAY <<< "$item"
     NAME="PCIDEVICE_OPENSHIFT_IO_${RES_ARRAY[1]^^}"
@@ -21,6 +23,7 @@ for item in "${NETWORK_ARRAY[@]}"; do
         echo "Could not find ${NAME} with PCI address, exiting"
         exit 1
     fi
+    echo "${NAME}=${!NAME}" >> $TESTPMD_ENV
     IFS=',' read -r -a PCI_ARRAY <<< "${!NAME}"
     for pci_item in "${PCI_ARRAY[@]}"; do
         PCI+=" -w ${pci_item} "
@@ -35,9 +38,15 @@ fi
 
 CORES_STR=$(expand-cpus)
 IFS=',' read -ra CORES_ARR <<< "$CORES_STR"
-CORES_SLICE="${CORES_ARR[@]:1}"
-CORES_SPACE="${CORES_SLICE[*]}"
-LCORES="${CORES_SPACE//${IFS:0:1}/,}"
+CORES_LEN=${#CORES_ARR[@]}
+if [[ $CORES_LEN -gt $TESTPMD_CPU_COUNT ]]; then
+    echo "ERROR: Acutal cores (${CORES_LEN}) is greater than configured cores (${TESTPMD_CPU_COUNT})"
+    exit 1
+fi
+
+#CORES_SLICE="${CORES_ARR[@]:1}"
+#CORES_SPACE="${CORES_SLICE[*]}"
+#LCORES="${CORES_SPACE//${IFS:0:1}/,}"
 
 STATS_PERIOD=${stats_period:=1}
 RUN="/usr/local/bin/testpmd-run"
@@ -47,8 +56,8 @@ chmod +x $RUN
 # Fetches mac address from pci using macaddr DPDK custom application
 # Mac address is written to tile /tmp/macaddr.txt
 # Fetch macaddress before running testpmd to avoid resource busy error
-if [ -f /tmp/macaddr.txt ]; then
-    rm -f /tmp/macaddr.txt
+if [ -f /var/lib/testpmd/macaddr.txt ]; then
+    rm -f /var/lib/testpmd/macaddr.txt
 fi
 n=0
 until [ "$n" -ge 5 ]; do
@@ -59,7 +68,6 @@ done
 
 function sig_term() {
     echo $(date +"%F %T,%3N") > /var/log/testpmd/sigterm-received.log
-    #sleep 5
     # kill testpmd application
     kill -9 $(ps aux | grep -w stats-period | grep -v grep | awk '{print $2}')
     exit
@@ -68,11 +76,7 @@ trap sig_term SIGTERM
 
 RUN_APP=${run_app:=1}
 if [[ $RUN_APP == "1" ]]; then
-    testpmd-pre-configure &
-    testpmd-run &
+    testpmd-run
+else
+    sleep infinity
 fi
-
-while true; do
-    sleep 1
-done
-#sleep infinity
