Fix python script errors

diff --git a/scripts/trex-wrapper b/scripts/trex-wrapper
--- a/scripts/trex-wrapper
+++ b/scripts/trex-wrapper
@@ -15,15 +15,28 @@ trex-cfg-configure $CORES
 # Read the number of cores from the trex cfg
 # It is required as input via -c arg (for binary_search scripts of trafficgen)
 CORE_COUNT=$(grep ' c: ' /etc/trex_cfg.yaml | cut -d: -f2 | xargs)
+NUM_PORTS=$(grep ' port_limit: ' /etc/trex_cfg.yaml | cut -d: -f 2 | xargs)
 
 SERVER="/usr/local/bin/trex-server"
 chmod +x $SERVER
 $SERVER $CORE_COUNT &
 
-# TODO: Make mode configurable, binary search or continuous packet 
-#run-binary-search
+# wait for trex server to be ready
+count=60
+num_ports=0
+while [ ${count} -gt 0 -a ${num_ports} -lt $NUM_PORTS ]; do
+    sleep 1
+    num_ports=`netstat -tln | grep -E :4500\|:4501 | wc -l`
+    ((count--))
+done
+if [ ${num_ports} -eq $NUM_PORTS ]; then
+    echo "trex-server is ready"
+else
+    echo "ERROR: trex-server could not start properly, existing... "
+    exit 1
+fi
 
 run-trex
 
 echo "Complete..."
-#sleep infinity
+sleep infinity
